Update SVM_Image_Classification_Matching.ipynb
The code works if the function Binarize is not used (I have done some changes, it worked before of them!). I can't understand why, this is the error given:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-74-8fd01ed8f39c> in <module>()
      2 
      3 db_folder = 'Database' # Modify with the name of the folder containing the database.
----> 4 image_dataset = load_image_files(os.path.join(os.getcwd(),db_folder))

<ipython-input-73-98357824f61d> in load_image_files(container_path, dimension)
     36                     img_bin = binarize(img_resized)
     37                     img_den = gauss_denoise(img_bin)
---> 38                     temp_flat_data.append(HOG(img_den))
     39                     temp_target.append(sub_dir.name)
     40         subj_dataset = match_images(temp_flat_data, temp_target)

<ipython-input-69-617ffbd822a0> in HOG(image)
      5               pixels_per_cell=(4, 4),
      6               cells_per_block=(2, 2),
----> 7               block_norm='L2-Hys')
      8     return img

~\Anaconda3\lib\site-packages\skimage\feature\_hog.py in hog(image, orientations, pixels_per_cell, cells_per_block, block_norm, visualize, visualise, transform_sqrt, feature_vector, multichannel)
    209         g_col = g_col_by_ch[rr, cc, idcs_max]
    210     else:
--> 211         g_row, g_col = _hog_channel_gradient(image)
    212 
    213     """

~\Anaconda3\lib\site-packages\skimage\feature\_hog.py in _hog_channel_gradient(channel)
     37     g_row[0, :] = 0
     38     g_row[-1, :] = 0
---> 39     g_row[1:-1, :] = channel[2:, :] - channel[:-2, :]
     40     g_col = np.empty(channel.shape, dtype=np.double)
     41     g_col[:, 0] = 0

TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.


------------------------------------------

You can just skip the Binarize function and use the code with the preprocessing part